### ISSUE TITLE
Sending ganglia metric to logstash results in a ganglia udp listener died

### ISSUE THREAD

**Issue by berrytchaks** [logstash-plugins/logstash-input-ganglia#16]
Hi All,

I having been working on sending my ganglia metrics to logstash. This is my configuration
input{
   ganglia {
     host => "127.0.0.1"
     type => "ganglia"
  }
}
output {
    stdout {
       codec => rubydebug
    }
}
This configuration results in a the following exception in the file logstash.log
{:timestamp=>"2016-02-03T20:05:25.706000+0000", :message=>"ganglia udp listener died", :address=>"127.0.0.1:8649", :exception=>#<SocketError: bind: name or service not known>, :backtrace=>["org/jruby/ext/socket/RubyUDPSocket.java:160:in `bind'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-ganglia-2.0.4/lib/logstash/inputs/ganglia.rb:55:in `udp_listener'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-ganglia-2.0.4/lib/logstash/inputs/ganglia.rb:36:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:180:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:174:in `start_input'"], :level=>:warn}

It seem to me that I'm missing something but doesn't know where to search. Please can somebody help me in this task. It is very URGENT please.
Thanks.

**Comment by suyograo** [comment]
@berrytchaks is this still happening?

**Comment by berrytchaks** [comment]
@suyograo  thanks for the concern but this issue is fixed.

**Comment by Hammond95** [comment]
@berrytchaks This is still happening to me... there is any workaround to fix it?

**Comment by Hammond95** [comment]
https://gist.github.com/Hammond95/0248a1ee6d5e04d9f8598bf4f97bcd08
