### ISSUE TITLE
ganglia udp listener died: No method error

### ISSUE THREAD

**Issue by refraction-ray** [logstash-plugins/logstash-input-ganglia#23]
OS: Ubuntu 18.04 server
Version of Logstash: 6.8.0 by apt
Version of ganglia input plugin for Logstash: 3.1.4 directly shipped with logstash
Version of ganglia-monitor (gmond): 3.6.0 by apt

Both ganglia alone and logstash with filebeat input as ELK stack work well and as expected.
But when I want to integrate ganglia into logstash, some errors happen.

Relavant config for gmond, master is the hostname the machine. Ports 8649 is still open for 
centralized gmond udp recv while port 28649 is new for input to logstash.
```
udp_send_channel {
  host = master
  port = 8649
  ttl = 1
}
udp_send_channel {
  host = master
  port = 28649
  ttl = 1
}
```

By tcpdump, you can see we indeed receive UDP packets on port 28649

```
$ sudo tcpdump -vv -i enp0s31f6 'port 28649'
tcpdump: listening on enp0s31f6, link-type EN10MB (Ethernet), capture size 262144 bytes
23:30:56.129219 IP (tos 0x0, ttl 64, id 33523, offset 0, flags [DF], proto UDP (17), length 80)
    c1.57032 > master.28649: [udp sum ok] UDP, length 52
23:30:56.129234 IP (tos 0x0, ttl 64, id 33525, offset 0, flags [DF], proto UDP (17), length 68)
    c1.57032 > master.28649: [udp sum ok] UDP, length 40
```

The config of logstash is as simple as 
```
input {
  ganglia {
    port => 28649
  }
}

output {
  stdout {
    codec => rubydebug
  }
}
```

After restarting logstash, in the log of logstash, I only see the following repeat pattern and nothing else.

```
[INFO ][logstash.inputs.ganglia  ] Starting ganglia udp listener {:address=>"0.0.0.0:28649"}
[WARN ][logstash.inputs.ganglia  ] ganglia udp listener died {:address=>"0.0.0.0:28649", :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-ganglia-3.1.4/lib/logstash/inputs/ganglia.rb:117:in `block in parse_packet'", "org/jruby/RubyArray.java:1792:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-ganglia-3.1.4/lib/logstash/inputs/ganglia.rb:116:in `parse_packet'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-ganglia-3.1.4/lib/logstash/inputs/ganglia.rb:71:in `udp_listener'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-ganglia-3.1.4/lib/logstash/inputs/ganglia.rb:36:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:426:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:420:in `block in start_input'"]}
```

Maybe someone could kindly help me out of this?

**Comment by amcneill3** [comment]
I also have this issue

OS: Red Hat Enterprise Linux Server release 7.4 (Maipo)
Version of Logstash: logstash-6.8.0-1.noarch
Version of ganglia input plugin for Logstash: 3.1.4 directly shipped with logstash
Version of ganglia-monitor (gmond): gmond 3.7.2

input {
  ganglia {
    port => 19649
    type => ganglia
    id => "pace_ganglia"
  }
}

output {
  elasticsearch {
    hosts => ["https://elk.pace.gatech.edu:9200"]
    index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
# snip ssl sensitive info
  }
  stdout {
    codec => rubydebug
  }
}

_________
snippet from logstash-plain.log:

[2019-07-08T14:57:22,427][INFO ][logstash.inputs.ganglia  ] Starting ganglia udp listener {:address=>"0.0.0.0:19649"}
[2019-07-08T14:57:23,383][WARN ][logstash.inputs.ganglia  ] ganglia udp listener died {:address=>"0.0.0.0:19649", :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-ganglia-3.1.4/lib/logstash/inputs/ganglia.rb:117:in `block in parse_packet'", "org/jruby/RubyArray.java:1792:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-ganglia-3.1.4/lib/logstash/inputs/ganglia.rb:116:in `parse_packet'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-ganglia-3.1.4/lib/logstash/inputs/ganglia.rb:71:in `udp_listener'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-ganglia-3.1.4/lib/logstash/inputs/ganglia.rb:36:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:426:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:420:in `block in start_input'"]}
[2019-07-08T14:57:28,383][INFO ][logstash.inputs.ganglia  ] Starting ganglia udp listener {:address=>"0.0.0.0:19649"}

_______
relevant gmond.conf bits on client node:

udp_send_channel {
 host = elk.pace.gatech.edu
 port = 19649
 ttl = 1
}

udp_recv_channel { 
 port = 19648
 }

tcp_accept_channel { 
 port = 19648 
}

**Comment by chlim-ias** [comment]
I am also having this issue, after following this guide https://gist.github.com/Hammond95/0248a1ee6d5e04d9f8598bf4f97bcd08
